# .travis.yml

language: ruby
rvm: 2.6.3

install:
  # Install binary pandoc from Rstudio
  # To use Pandoc, uncomment the following
  # - export PATH="$HOME/pandoc:$PATH"
  # - mkdir $HOME/pandoc
  # - curl -O https://s3.amazonaws.com/rstudio-buildtools/pandoc-1.13.1.zip
  # - unzip -j pandoc-1.13.1.zip pandoc-1.13.1/linux/debian/x86_64/pandoc
  #     -d $HOME/pandoc
  # - chmod +x $HOME/pandoc/pandoc
  # - pandoc --version

  # Install Jekyll and dependencies
  - gem update github-pages
  
  - bundle install

  - bundle update github-pages

script: bundle exec jekyll build

branches:
  only:
    - master
