# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software engineering experiencies related blog
email: enricfj@gmail.com
description: Enric Forn  Innovation and Architecture Product Manager
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'https://enricforn.gihub.io/' # The base hostname & protocol for your site
github_username:  enricforn
twitter_username: eforn
linkedin_username: in/enricforn

# Fill in your Google Analytics gtag.js ID to track your website using gtag
gtag: "UA-9183934-11"
markdown:  kramdown
permalink: pretty
paginate:  12

plugins:
  - jekyll-include-cache
  - jekyll-paginate
# - jekyll-sitemap
# - jekyll-feed
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  eforn:
    name: Enric Forn
    display_name: Enric Forn
    bio: Software development, software automation, DevOps, Innovation, distributed teams
    gravatar: https://ca.gravatar.com/userimage/31031445/c8f5726b05036ffefcbd5afbe484f2da.jpg
    linkedin: enricforn
    github: enricforn
    twitter: eforn
    email: enricfj@gmail.com