# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Software engineering experiencies related blog
email: enricfj@gmail.com
description: Enric Forn  Innovation and Engineering Manager
baseurl:          '' # The subpath of your site, e.g. /blog
url:              'http://enricforn.gihub.io/' # The base hostname & protocol for your site
github_username:  enricforn
twitter_username: eforn
linkedin_username: in/enricforn

markdown:  kramdown
permalink: pretty
paginate:  12

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  eforn:
    name: Enric Forn
    display_name: Enric Forn
    bio: Software development, software automation, DevOps, Learning, distributed teams
    gravatar: http://www.gravatar.com/avatar/{{e4306225c5593de4b39fa7f66d49f81b}}?s=35
    linkedin: enricforn
    github: enricforn
    twitter: eforn
    email: enricfj@gmail.com